export const AUTH_MESSAGES = {
  START_GOOGLE_SIGN_IN: 'START_GOOGLE_SIGN_IN',
  GOOGLE_SIGN_IN: 'GOOGLE_SIGN_IN',
  OFFSCREEN_GOOGLE_SIGN_IN: 'OFFSCREEN_GOOGLE_SIGN_IN',
  FIREBASE_GOOGLE_SIGN_IN: 'FIREBASE_GOOGLE_SIGN_IN',
  SERVICE_WORKER_PING: 'SERVICE_WORKER_PING',
  PING_BACKGROUND: 'PING_BACKGROUND',
  SERVICE_WORKER_PONG: 'SERVICE_WORKER_PONG',
} as const;

export const AuthMessages = AUTH_MESSAGES;

